### ISSUE TITLE
Cricket 07 error

### ISSUE THREAD

**Issue by retrobone** [crosire/d3d8to9#135]
I tried playing with the wrapper but the game just crashes at the startup and won't launch.

**Comment by gabberworld** [comment]
i to have also game crashing with other ea sports game, but for me its like 50/50 it works but it also crash in some situation

**Comment by retrobone** [comment]
Yeah, Cricket 2002 and Cricket 2004 get black models whereas Cricket 2005 which came before and is completely based on the same engine as Cricket 2007 runs with d3d8to9 flawlessly.

**Comment by Bepec23** [comment]
Still crash at startup

**Comment by crosire** [comment]
Closing, since this had been fixed by #108.

**Comment by elishacloud** [comment]
@crosire, I am getting user reports that this game still crashes with d3d8to9.  See here:  https://github.com/elishacloud/dxwrapper/issues/352#issuecomment-2764430414

**Comment by crosire** [comment]
Different issue than what's mentioned in the posted log then.
